[project]
name = "langchain-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sourabh_upadhye", email = "srazor11@email.com" }
]
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.2",
    "langchain>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.6",
    "pre-commit>=4.6.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langchain-ai = "langchain_ai:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
