[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.git
  |JenkinsFile
)/
'''

[tool.ruff]
line-length = 100
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741"]

[tool.djlint]
profile="django"
